language: node_js
sudo: false
node_js:
  - '10'
  - '12'

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn run lint && yarn run cover

after_success:
  - ./node_modules/.bin/codecov
